### ISSUE TITLE
Use signcolumn instead of linenr column

### ISSUE THREAD

**Issue by yochem** [mawkler/hml.nvim#1]
See [:h signcolumn](https://neovim.io/doc/user/options.html#'signcolumn'). 

For example, it would place these markers in the column with my fold and diagnostic signs, on the leftside of the linenumbers.

<img width="498" alt="Screenshot 2024-11-20 at 12 42 35" src="https://github.com/user-attachments/assets/e109b3dc-f6ff-4f29-a07b-4553ef66fb85">

I could take a look at it. As legacy option, placing it in linenumber column could still be supported (or people could use `:set signcolumn=number`).

**Comment by yochem** [comment]
It also currently doesn't work for me using https://github.com/luukvbaal/statuscol.nvim.

**Comment by mawkler** [comment]
@yochem I personally prefer having them in the number column. But you should be able to implement this using `require('hml').get()` to determine what lines to place `H`/`M`/`L` on. If the PR doesn't add too much complexity I might consider adding it as an option 🙂

statuscol.nvim seems to be its own status column configuration framework, so you'll have implement `H`/`M`/`L` functionality for statuscol.nvim yourself using the `require('hml').get()` method mentioned above.

**Comment by yochem** [comment]
Oh that's great! I might use that. The code is more or less the following (not much tested yet):

```lua
local ns = vim.api.nvim_create_namespace("hml")

vim.api.nvim_create_autocmd({ "CursorHold" }, {
  callback = function()
    vim.schedule(function()
      vim.api.nvim_buf_clear_namespace(0, ns, 0, -1)

      local signs = get()
      for sym, linenr in pairs(signs) do
        vim.api.nvim_buf_set_extmark(vim.api.nvim_get_current_buf(), ns, linenr - 1, 0, {
          sign_text = sym,
        })
      end
    end)
  end,
  group = vim.api.nvim_create_augroup("hml", {})
})

```

**Comment by yochem** [comment]
Hey, I was playing with this project and thought it would be nice to be able to add other jump locations as well. Because this would probably be beyond the scope of your plugin (guessing based on the name ;)), I started a repo for it: https://github.com/yochem/jumpsigns.nvim. The calculations of the sign linenumbers is based on your `M.get()` function. Let me know if this is alright with you, or if there is something that I can change. I mentioned this repo in the readme of course.

**Comment by mawkler** [comment]
@yochem That's great! Thanks for the mention in your readme! I've added an MIT license to this repo now as well.
